# Generated by Django 4.0.8 on 2022-10-15 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mechanicus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access this app'), ('job_view_open_access', 'View access to open or unassigned jobs'), ('job_view_all_access', 'View access to all jobs')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillId', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_assignee_set', to=settings.AUTH_USER_MODEL)),
                ('assigner', models.ForeignKey(blank=True, default=mechanicus.models.Job.get_mechanicus_service_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_assigner_set', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_creator_set', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_parent_set', to='mechanicus.job')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mechanicus.blueprint')),
                ('root', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_root_set', to='mechanicus.job')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkillMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.evecharacter')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanicus.skill')),
            ],
        ),
        migrations.CreateModel(
            name='BlueprintSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanicus.blueprint')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanicus.item')),
            ],
        ),
        migrations.CreateModel(
            name='BlueprintOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanicus.blueprint')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanicus.item')),
            ],
        ),
        migrations.CreateModel(
            name='BlueprintInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanicus.blueprint')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanicus.item')),
            ],
        ),
    ]
