# Generated by Django 4.0.8 on 2022-10-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicus', '0002_blueprint_blueprintid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='blueprintId',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemId',
            field=models.IntegerField(unique=True),
        ),
    ]
