# Generated by Django 4.0.8 on 2022-10-15 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechanicus', '0003_alter_blueprint_blueprintid_alter_item_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanicus.skill'),
        ),
    ]
